apiVersion: v1
kind: Service
metadata:
  labels:
    app: multiclusterhub-repo
  name: multiclusterhub-repo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: multiclusterhub-repo